services:
  db:
    image: postgres:14
    container_name: postgres_db_poow1
    restart: always
    environment:
      POSTGRES_DB: poow_trabalho
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      # Este volume executa o script SQL na primeira inicialização
      - ./poow_trabalho.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    # IMPORTANTE: Usa a imagem que vamos construir, e não tenta construir de novo.
    image: minha-biblioteca-app
    container_name: wildfly_app_poow1
    restart: always
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - ./logs:/opt/jboss/wildfly/standalone/log
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: poow_trabalho
      DB_USER: postgres
      DB_PASS: 1234

volumes:
  db_data:
