# Define os serviços (containers) que farão parte da nossa aplicação.
services:
  # Serviço para o banco de dados PostgreSQL.
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: poow_trabalho
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      # Inicializa o banco de dados com o seu script SQL.
      - ./poow_trabalho.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  # Serviço para a sua aplicação Java (biblioteca).
  app:
    container_name: biblioteca_app
    build: .
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    # NOVO: Monta um volume para os logs do Tomcat.
    # A pasta 'logs' será criada no seu diretório do projeto
    # e conterá os logs gerados pelo servidor Tomcat dentro do container.
    volumes:
      - ./logs:/usr/local/tomcat/logs
    depends_on:
      - db