# serviços (containers)
services:
  # banco de dados PostgreSQL
  db:
    # imagem oficial do PostgreSQL na versão 13 - vem pronta do Docker Hub
    image: postgres:13
    # nome do container - identificação
    container_name: postgres_db
    # variáveis de ambiente para configurar o banco de dados - nome, usuário e senha
    environment:
      POSTGRES_DB: poow_trabalho
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      # mapeia o script SQL local para a pasta dentro do container, onde o PostgreSQL executa scripts de inicialização
      # cria tabelas e insere dados iniciais
      - ./poow_trabalho.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      # mapeia a porta 5433 do host para a porta 5432 do container
      - "5433:5432"

  # aplicação java (biblioteca)
  app:
    container_name: biblioteca_app
    # Docker Compose vai construir a imagem a partir do Dockerfile, no diretório atual
    build: .
    environment:
      # serviço 'db' vira um hostname válido
      DB_HOST: db
    # expõe a porta 8080 do container para a porta 8080 do host
    ports:
      - "8080:8080"
    # a pasta 'logs' é criada no diretório do projeto, com os logs gerados pelo Tomcat dentro do container
    volumes:
      - ./logs:/usr/local/tomcat/logs
    # o container da aplicação só inicia com o banco de dados pronto
    depends_on:
      - db